INSTALL.txt
Updating the git url to point to this repo instead of the python2 one.
=> Update the repo url in the install documentation

INSTALL.txt
This has some minor fixes for typo and grammar errors in INSTALL.txt.
Also includes some formatting and wording adjustments to make it internally consistent, and to match GitHub's styling of their name.
=> INSTALL.txt: Minor typo fixes and style tweaks

html5.conf, xhtml11.conf
The old link (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML) was retired and is recommended to be replaced with a link to cloudflare's cdnjs.
=> Update MathJax CDN link

Dockerfile
This is a part of the work from #38 (which I didn't notice till now was closed after I messed up doing merges on my fork) and is necessary for carrying out #21. This makes it so that we can easily test on a range of python versions, but remain on the same base (Debian Stretch) so that we don't end up with different versions of the other dependencies of asciidoc (namely libpng/lilypond) which cause the tests to fail then.
=> Update Dockerfile to better allow using different python versions

filters/graphviz/graphviz2png.py
Moving `graphviz2png.py` from optparse to argparse as mentioned in #4 
I had to fix the following issue when generating from a file and not from the input directly (which is the change in the `run` function) to make it work:
```
Traceback (most recent call last):                                
File "filters/graphviz/graphviz2png.py", line 161, in <module>                   
app.run()                                                                                      
File "filters/graphviz/graphviz2png.py", line 145, in run                                                                                                    
if not os.path.isfile(infile):
UnboundLocalError: local variable 'infile' referenced before assignment
```
Tested the generation via input string:
```
echo "digraph G …
```
=> Move graphviz2png to argparse and fix a variable unassigned before use

asciidoc.conf, asciidoc.py, docbook45.conf, docbook5.conf, html5.conf, latex.conf, xhtml11.conf
Remove some forgotten `(?u)` in regex as now we are in python3, keeping them is useless.
Most of them had already been removed anyway. That's just a cleanup.
=> Remove deprecated unicode option on regex

tests/testasciidoc.py
Fixes using `--number` for `./tests/testasciidoc.py` to select a specific test.
=> Fix using number flag for testasciidoc.py

MANIFEST.in
Missing some files in the MANIFEST.in file for the python3 packaging which causes it to not run properly.
Can be tested from https://test.pypi.org/project/asciidoc/
=> Add in missing .css and .js files to MANIFEST.in

a2x.py
No functionality was changed, just a best practices change of not overwriting python builtins as it can create surprising behavior for people.
=> Fix a2x overwriting builtin zip function

README.asciidoc
The README's current "Obtaining AsciiDoc" section text points to asciidoc.org, which describes the old Python 2 version. This PR updates the text to point to the under-development asciidoc-py3 project.
Open to suggestions for improving the wording here.
=> README: Update "Obtaining" for under-development asciidoc-py3

.travis.yml, CHANGELOG.txt, INSTALL.txt, README.asciidoc, asciidoc.py, asciidocapi.py
Closes #64 
Drops 3.4 support as it was EOL back in March and it's recommended that one upgrade to 3.5+ to enjoy new features, bugfixes, etc.
This does lack some changes that'll be necessary for the repackage branch in setup.py
=> Drop python 3.4 support

doc/testasciidoc.1.txt, tests/testasciidoc.py
The idea is to be consistent overall by providing short versions for all our args (except for `--force` which is most of the time not shortened anyway) as there are some which have the short version.
=> Add short version of args to testasciidoc

Makefile.in
Continued work on #44 / #83 in translating the *.aap targets to makefile targets.
This unifies the spell target in `doc/` and `examples/website/` to a top-level `make spell` with each also having their own target of `doc_spell` and `website_spell` to retain capacity of checking just one.
=> Add makefile target for spell checking

asciidocapi.py
Hi guys!
As describe by Simon in [Debian bug #945391](https://bugs.debian.org/945391), when trying to instantiate the asciidocapi with the version I put in Debian based on commit 51d7c14, the loader fails:
```
$ python3
Python 3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> import sys
>>> sys.path.append('/usr/share/asciidoc')
>>> import asciidocapi
>>> infile = io.StringIO('Test')
>>> outfile = io.StringIO()
>>> adoc = asciidocapi.AsciiDocAPI()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/share/asciidoc/asciidocapi.py", line 209, in __init__
self.__import_asciidoc()
File "/usr/share/asciidoc/asciidocapi.py", line 244, in __import_asciidoc …
```
=> asciidocapi: Fix crash  on load of the loader

.travis.yml
It's expected that all test files exist within the repo and Travis should not be responsible for creating/updating any. This should make it clearer for when a PR might break the existing test cases or require updating them.
=> remove testasciidoc.py update line from travis

.travis.yml, Makefile.in
Running `make` or `make all` would run the `aspell` command for a couple files as the file is included in two different make targets. This fixes the spell commands to not utilize the file-based make targets, but just use a for loop instead.
Travis has been updated to include `make` as one of its build commands to ensure that runs as expected going forward.
closes #89
=> Fix make all incorrectly including spell command for couple files

vim/syntax/asciidoc.vim
Hi guys,
The removal of those lines were requested in Debian to speed up vim's refresh process on big files: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=767179
It has been there for over 2 years now so I thought I might just push it here too (I'll push it in the vim-asciidoc repo too to keep them in sync while the transition is being done) :)
Thanks,
Joseph
=> vim-asciidoc: speed up the refresh process for big files

.travis.yml
Looks like Travis-CI changed something on their backend that is causing `install: false` to now fail builds. `install: true` should work better, even if it's a bit less intuitive looking (as I guess now Travis is truly executing the `false` / `true` shell commands and directly using their exit codes (`1` / `0` respectively).
=> Use true for skipping install section for travis

examples/website/index.txt
=> Add note that Fedora Docs uses AsciiDoc.

CHANGELOG.txt, a2x.py
Note: This is the same as #93 except that it does not use f-strings (which was causing problems with Python 3.5).  I have not done the more sophisticated encoding updates that we discussed, but when I saw that @MasterOdin had #101 out as a stop gap, I decided to update my earlier development.
As an alternative to passing all of the options on the command line, a2x allows one to specify options in the body of the text of the source file (e.g. lines starting with "//a2x: <option>" will have "<option>" processed as if it was on the command line).  Even if a user does not use this feature, a2x will always perform the scan.
The code that scans the input file for options does not specify an encoding.  So, in those cases where the actual encoding of the file does not match the locale (e.g. input …
=> Fix a2x Option Collection From Input File With Non-ASCII Encoding (Take 2)

CHANGELOG.txt, tests/testasciidoc.conf, tests/testasciidoc.py
Part of work for #99 
Adds a new `% requires` directive for the testasciidoc.conf file. This directive is a list of command-line utilities that must exist for that particular test to run.
For example:
```
Additional Open Block and Paragraph styles
% requires
['source-highlight', 'dot']
% source
data/open-block-test.txt
```
This will check that `source-highlight` and `dot` exist (using `shutil.which`) and if one of them does not, the test is skipped.
Does this fit your needs @aerostitch for your second point?
=> add requires directive to testasciidoc

INSTALL.txt, doc/a2x.1.txt, doc/asciidoc.1.txt, doc/testasciidoc.txt, tests/data/asciidoc.1-docbook.xml, tests/data/asciidoc.1-docbook5.xml, tests/data/asciidoc.1-html4.html, tests/data/asciidoc.1-html5.html, tests/data/asciidoc.1-xhtml11.html, website/README-website.txt, website/index.txt, website/support.txt
This begins the process of updating the website to more accurately reflect the reality of asciidoc-py3.
I have not gone through the numerous external links to find which are dead and remove them. That will happen in a subsequent PR focused on that.
=> update information on website to be more up-to-date about asciidoc-py3

CHANGELOG.txt, doc/asciidoc.txt, docbook45.conf, docbook5.conf, tests/data/testcases-docbook.xml, tests/data/testcases-docbook5.xml, tests/data/testcases-html4.html, tests/data/testcases-html5.html, tests/data/testcases-xhtml11.html, tests/data/testcases.txt
dblatex permits setting the floating attribute for figures, examples, equations and tables by specifying the floatstyle attribute.  example xsl shown below:
```xml
<xsl:template match="figure">
<xsl:text>\begin{figure}</xsl:text>
<xsl:choose>
<xsl:when test="@floatstyle != ''">
<xsl:value-of select="@floatstyle"/>
</xsl:when>
<xsl:when test="not(@float) or (@float and @float='0')">
<xsl:text>[H]</xsl:text>
</xsl:when>
<xsl:otherwise>
<xsl:value-of select="$figure.default.position"/>
</xsl:otherwise>
</xsl:choose>
<xsl:text>&#10;</xsl:text>
```
```xml
<xsl:value-of select="concat('\begin{', $table.env, '}')"/>
<xsl:choose>
<xsl:when test="@floatstyle != ''">
<xsl:value-of select="@floatstyle"/>
</xsl:when>
<xsl:otherwise>
<xsl:value-of select="$table.default.position"/>
</xsl:otherwise> …
```
=> allow floating dblatex figures, examples, equations and tables with floatstyle attribute

asciidoc.py
The [`lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache) is used to create a cache of function calls to results. As the `macros.match` function is called a lot, usually with the same arguments, we can utilize this function to store the results between calls. While I could set the max_items parameter to be higher here, increasing it by 100x only really amounts to a ~0.02s speed-up or so, at the cost of more memory being consumed during parsing. Better speed-ups would be to rewrite the macro system such that missed calls then fall-back to utilize something like out of #49.
=> use lru_cache for macros.match

COPYRIGHT, README.asciidoc, a2x.py, asciidoc.py, asciidocapi.py, doc/a2x.1.txt, doc/asciidoc.1.txt, doc/asciidoc.txt, filters/code/code-filter.py, filters/latex/latex2img.py, filters/music/music2png.py, help.conf, tests/data/asciidoc.1-docbook.xml, tests/data/asciidoc.1-docbook5.xml, tests/data/asciidoc.1-html4.html, tests/data/asciidoc.1-html5.html, tests/data/asciidoc.1-xhtml11.html, tests/testasciidoc.py, website/index.txt
This unifies and updates the copyright notice across the codebase such that the time Stuart worked on it (till about Nov 2013) and then after that it was handled by just the generic "AsciiDoc Contributors" byline. Can update this to put a specific person's name if requested.
I've also made it clear that the codebase is licensed under GPLv2 throughout where GPL was used, and added the full MIT license text to a2x as that's under the MIT for some reason.
=> update copyright notice to include generic asciidoc contributors

a2x.py
Fixes #124
The regex for finding encoding of a document currently only works for xml files, not html ones. This adds an additional check to get that for html files.
=> fix a2x failing on parsing encoding of html files

a2x.py
This reverts commit e3fd0a7de6fe0f24f8e671720bf3c9ed9c18005e (#34).
As pointed out in https://github.com/asciidoc/asciidoc-py3/pull/34#issuecomment-653959566 and subsequent comments, moving to argparse broke how some people were utilizing a2x command line parsing. While it's debatable on the validity of how the command line options were being specified, at the end of the day, the 9.x release line is meant to be a straight move for people from python2 to python3 without anything about their pipelines breaking. As such, reverting this PR for now, though it's possible it will be merged back at a later date in the 10.x line, I am undecided on this.
=> Revert "Moving a2x from optparse to argparse (#34)"

README.asciidoc, website/layout2.conf
As part of the formation of the AsciiDoc Working Group at the Eclipse Foundation, the AsciiDoc trademark was transferred to the Eclipse Foundation in order to protect it. Since the AsciiDoc Python project predated the creation of the Working Group, and in fact originated the language, it is permitted to continue using "AsciiDoc" in the project name, even without demonstrating compliance (though my hope is that it eventually will, in some form). However, what is required is to add a notice to the README and website footer that AsciiDoc is a trademark of the Eclipse Foundation, Inc. That's the change proposed by this PR.
If you have any questions are concerns, please feel free to raise them.
=> add AsciiDoc trademark notice to README and website footer

tests/testasciidoc.py
$SOURCE_DATE_EPOCH is now the officially supported mechanism for guaranteeing stable output timestamps, which means we can simply run the tests using that, and drop some code.
This also fixes #131 since the variable would override the mocked time, resulting in tests failing if $SOURCE_DATE_EPOCH was set in the environment (e.g. for linux distro packaging).
=> tests: simplify timestamp mocking

MANIFEST.in
Closes #136 
The generated `./doc/testasciidoc.1` will now be included within the release assets.
=> Add testasciidoc.1 to MANIFEST.in for release assets

.github/workflows/test.yml
This puts into place a CI run for testing asciidoc on windows, though only on a minimal example, due to it lacking much of the dependencies that are easy to install on Linux. This will help validate behavior to ensure things work same on both platforms, sans filters. Related to #139
=> add simple CI test for running asciidoc on windows

asciidoc.py
In case we ever want to change the line ending that asciidoc uses, this consolidates the four usages of `\r\n` to a global constant. This global constant will also be used in a future PR within the test suite to ensure it's also using that line ending for generated test results, instead of `os.linesep` as currently.
=> define default newline to use as global constant

tests/testasciidoc.py
Currently, the testasciidoc.py when generating the test results will use the OS' line separator, which means that all of the generated files, which were created on Linux, use `\n` as the line ending. This makes it so that we use the default line ending for generating the files, which will then be used in a future PR to ensure that asciidoc is writing out the files as expected with the right line endings.
After merging this, the next PRs are:
* Update all of the generated test data to use the new line endings
* Update the tests to actually consider line endings as part of the diff check
=> use DEFAULT_NEWLINE constant for line ending for generated test sources

tests/testasciidoc.py
This changes the output when doing `python3 tests/testasciidoc.py update` to better match the output when doing `run` by printing out the source per file, and then also inserting a newline between blocks of files. Makes things to parse in my opinion:
Old output:
```
WRITING: tests/data/testcases-html4.html
WRITING: tests/data/testcases-xhtml11.html
WRITING: tests/data/testcases-docbook.xml
WRITING: tests/data/testcases-docbook5.xml
WRITING: tests/data/testcases-html5.html
WRITING: tests/data/newtables-html4.html
WRITING: tests/data/newtables-xhtml11.html
WRITING: tests/data/newtables-docbook.xml
WRITING: tests/data/newtables-docbook5.xml
WRITING: tests/data/newtables-html5.html
```
new output:
```text
SOURCE: asciidoc: tests/data/testcases.txt
WRITING: tests/data/testcases-html4.html …
```
=> print source file when updating test data

CHANGELOG.txt, a2x.py, asciidoc.py, configure.ac
```
Version 9.0.3 (2020-10-05)
--------------------------
.Bug fixes
- Fix extra newline characters inserted into generated source (thanks @hoadlck)
.Testing
- Validate line endings as part of test suite
=> v9.0.3 release

CHANGELOG.txt, a2x.py, asciidoc.py, configure.ac
```
Version 9.0.4 (2020-10-20)
--------------------------
.Bug fixes
- Fix listing out installed plugins (e.g. --filter list)
.Testing
- Update to deadsnakes/python@v2.0.0 for testing dev python versions
- Move from testing against 3.9-dev to stable 3.9
```
=> cut v9.0.4 release

CHANGELOG.txt
Correct name of person that fixed Python version check in #151.
It was @hroncok not I.
=> Fix incorrect attribution for Python version check.

website/index.txt
This is related to #159 and #114.
I made each change in a separate commit, and in some cases added some extra context on the change.  I am pretty confident in these changes: the ones that were less clear I documented in the issue.
I also think it would be a good idea to update all of the links to https (for site SEO reasons).  However, there were some of the servers did not have good certificates, so you get a scary message from the browser.  And, I did not really want to go thru and test each site one by one tonight....
=> Fix asciidoc.org Link Rot (Part 1)

CHANGELOG.txt, a2x.py, asciidoc.py, configure.ac
```
Version 9.0.5 (2020-12-12)
--------------------------
.Bug fixes
- Use config newline setting in system attribute evaulation (thanks @hoadlck)
.Testing
- Update to deadsnakes/python@v2.0.2
```
=> cut 9.0.5 release

.gitignore, asciidoc/asciidoc.py, tests/data/dummy_file.py, tests/data/include-lines-html5.html, tests/data/include-lines-test.txt, tests/testasciidoc.conf
Closes #149 
This enables support for using `lines` as an attribute to the `include` directive, like so:
`include::../testasciidoc.py[lines="29..44,61..68,70,398..-1"]`
It also supports the usage of the semi-colon for looking to the future when the `"` marks are not required.
=> add support for lines attribute for include directive
